/**
 * Copy the seeded dataset into the REMOTE D1 database.
 *
 *     bun run db:seed          # build the dataset locally first
 *     bun run db:seed:remote   # then push it to the deployed database
 *
 * Why this exists: `tools/seed.ts` writes through `bun:sqlite` and refuses to touch anything
 * that is not a local file, which is the right default — it deletes every domain row before
 * it inserts. A fresh remote database has no accounts at all, and sign-up is disabled
 * (`disableSignUp`, FR08), so without this there is no way to sign in to a deployment.
 *
 * It reads the local database rather than duplicating the dataset, so the two can never
 * disagree, and it copies the password hashes verbatim: the accounts seeded here are the
 * ones documented in the README.
 *
 * The generated SQL deletes each table before inserting, so running it twice is safe.
 */
import { Database } from 'bun:sqlite'
import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const D1_DIR = '.wrangler/state/v3/d1/miniflare-D1DatabaseObject'
const DB_NAME = 'hmti-inventaris'
const SQL_PATH = '.wrangler/seed-remote.sql'

/**
 * Parents before children, so foreign keys hold while the file runs. `session` and
 * `verification` are deliberately absent: sessions belong to whoever is signed in, and the
 * verification rows are single-use auth artefacts.
 */
const TABLES = [
  'kategori',
  'barang',
  'user',
  'account',
  'pengajuan',
  'pengajuan_barang',
  'surat',
  'serah_terima',
  'serah_terima_item',
  'pengembalian',
  'pengembalian_item',
  'log_aktivitas',
] as const

function findLocalDb(): string {
  const files = readdirSync(D1_DIR)
    .filter((f) => f.endsWith('.sqlite') && f !== 'metadata.sqlite')
    .map((f) => join(D1_DIR, f))
  if (files.length === 0) {
    throw new Error(
      `No local D1 database in ${D1_DIR}. Run \`bun run db:migrate:local\` then \`bun run db:seed\`.`,
    )
  }
  if (files.length > 1) {
    throw new Error(
      `Several local databases found; refusing to guess:\n  ${files.join('\n  ')}`,
    )
  }
  const f = files[0]
  if (!f.startsWith('.wrangler')) {
    throw new Error(`Refusing to read a non-local database: ${f}`)
  }
  return f
}

/** A SQL literal for one column value. Everything the seed writes is text, number or null. */
function literal(v: unknown): string {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'bigint') return String(v)
  if (v instanceof Uint8Array) {
    return `X'${Array.from(v, (b) => b.toString(16).padStart(2, '0')).join('')}'`
  }
  return `'${String(v).replace(/'/g, "''")}'`
}

function main() {
  const path = findLocalDb()
  const db = new Database(path)
  const lines: string[] = [
    '-- Generated by tools/seed-remote.ts. Deletes and re-inserts the demo dataset.',
    'PRAGMA foreign_keys = OFF;',
  ]

  let total = 0
  for (const t of [...TABLES].reverse()) lines.push(`DELETE FROM "${t}";`)
  for (const t of TABLES) {
    const rows = db.query(`SELECT * FROM "${t}"`).all() as Record<
      string,
      unknown
    >[]
    if (rows.length === 0) continue
    const cols = Object.keys(rows[0])
    for (const row of rows) {
      lines.push(
        `INSERT INTO "${t}" (${cols.map((c) => `"${c}"`).join(', ')}) VALUES (${cols
          .map((c) => literal(row[c]))
          .join(', ')});`,
      )
    }
    total += rows.length
  }
  lines.push('PRAGMA foreign_keys = ON;')
  db.close()

  writeFileSync(SQL_PATH, `${lines.join('\n')}\n`)
  console.log(
    `Wrote ${SQL_PATH}: ${total} rows across ${TABLES.length} tables.`,
  )
  console.log(
    `Now apply it:  bunx wrangler d1 execute ${DB_NAME} --remote --file=${SQL_PATH} -y`,
  )
}

main()
